#!/bin/sh
mvn clean package && docker build -t muzammilnagariya/MSASecondClient .
docker rm -f MSASecondClient 2>/dev/null || true && docker run -it --name MSASecondClient -p 8080:8080 -p 4848:4848 -p 8181:8181 --name MSASecondClient muzammilnagariya/MSASecondClient
